
;======== Translations to ENGLISH ======== by fonpaolo.deviantart.com ========

;Feel free to edit as you like the translation or if you find an error.

;If you want, you can make a new translation in another language not existing in the list.
;Use "Language Guide.txt" as a translation guide, copy and paste the translated text to create the correct language translation.


;REMEMBER: SAVE AS... with the new language abbreviation, for example, "Espanol" -> save as -> "LanguageES.inc"


[Variables]

;DATE ===========================================

DateMonthList=

DaysList=

Year=Year

;CALENDAR =======================================

TitleCAL=Calendar
WeekN=WEEK
Nof=of
Days=DAYS
DayTot=DAY
Rem=REMAINING
Seasons="1":"WINTER","2":"SPRING","3":"SUMMER","4":"AUTUMN"
Calendar1=Close Calendar
Calendar2=Open Calendar
CalendOpt=Start month with
CalendTooltip=Sunday or Monday
DayCal0=Sunday
DayCal1=Monday

; Change the first two letters of the day's name with your translation, this will show the name of the days in your current language.

Day1=Mo
Day2=Tu
Day3=We
Day4=Th
Day5=Fr
Day6=Sa
Day7=Su

;AV WEATHER =====================================

TitleW=WEATHER
Weather1=Close Weather
Weather2=Open Weather

Day=Day
Humidity=Humidity
IndexUV=Index UV
Night=Night
TodayT=Today
TonightT=Tonight
Tomorrow=Tomorrow
Updated at=Updated
Wind=Wind
WindGust=Wind Gust
WindChill=Wind Chill

TitleSat=Satellite view
TitleDet=Local identification
TitleDescr=Details current location

SunR=Sunrise:  
SunS=Sunset :  

MoreD1=Show details
MoreD2=Hide details
More1=Open Satellite view
More2=Close Satellite view
Lat=Latitude
Lon=Longitude
Press=Pressure
Tend=Tendency
Visib=Visibility
FeelsL=Feels like
West=W

DetailedWeatherList="N/A":"-"

DetailsList=

ConditionsList="Early ":""," Early":""," Late":"","Late ":"","PM ":"","AM ":""

ConditionsListN="Sunny":"Clear","Mostly Sunny":"Clear","Early ":""," Early":""," Late":"","Late ":"","PM ":"","AM ":"","Sun":"Clear"

AlertTxt="From:":"from:","Until:":"to:","jpg":"png"
Upd=Upd.
Hour=at
NoInfo1=Today    - No warnings
NoInfo2=Tomorrow - No warnings
MoreAlert1=Close WeatherAlert
MoreAlert2=Open WeatherAlert

;MUSIC ==========================================

TitleMP=Media
SpectrTitle=Spectrum analyzer
SpectrType1=Full - peak 1
SpectrType1a=Full - peak 2
SpectrType1b=Full - peak 3
SpectrType2=Bars only
SpectrType3=Maximum level only
SpectrPos=Update Spectrum position
NoArt="":"No Artist"
NoAlb="":"No Album"
NoTrk="":"No Title"
NoYear="^0$":"No Date"

;SHUTDOWN =======================================

SHDWN=ShutDown
REST=Restart
LGOFF=LogOff

;NOTES ==========================================

NoteT=Notes
CloseT=Close

Note1Txt=Memo
Note2Txt=To do
Note3Txt=Schedule
Note4Txt=List

;FEEDS ==========================================

FeedsT=Feeds
FeedUpdate=Update Feeds
FeedSrch=Searching data
FeedUpd=Last Update
FeedPost=Posted by
FeedDate="T":" at ","PDT":"","deltawp, p...":"","Statistics:":"","Posted by":""

;UPTIME =========================================

TitleUPT=Time Used
Upt1=d
Upt2=h
Upt3=m

UptDet1=Disable details window
UptDet2=Enable details window
UptDet3=Enable concealed details
UptDet4=Disable concealed details

;TIME ===========================================

InfoCLA1=Enable close on launch
InfoCLA2=Disable close on launch
TotTxt=Total
Free=Free
USBRem=Right click#CRLF#to eject

;LAUNCHERS 2 ====================================

SmLTxt1=Deactivate Launchers
SmLTxt2=Activate Launchers

;SYS LAUNCHERS ==================================

Sys1=System
Sys2=Devices
Sys3=Networks
Sys4=Performance
Sys5=Computer
Sys6=Memories

;SYS STATISTICS =================================

TitleT=Telemetry

;DISK STATISTICS ================================

TitleS=Surveillance

Sys7=Write
Sys8=Read

;WI-FI STATISTICS ===============================

TitleWF=Connections
TitleLabel=SYSTEM PERFORMANCE MONITORS
HideTitleLabel=Hide Title Label
ShowTitleLabel=Show Title Label

Sys9=Signal
Sys10=Upload
Sys11=Download

;AV RECYCLER ====================================

CleanTxt=Empty Bin
TitleREC=Recycler
REC1=items

;SYS MONITOR ====================================

TitleMON=Monitor
SysTxt1=Reduce
SysTxt2=Expand

;RES MONITOR ====================================

TitleRES=System Monitor

Res1=RAM Used
Res2=Used
Res3=SWAP Used
Res4=Battery
Res5=Status
BatteryStatus="0":"AC POWER","1":"CHARGING","2":"EMPTY","3":"LOW","4":"CHARGED"

;CPU ============================================

OSYS=Operating System
OpenTask=Open Task Manager

;NETWORK (Wi-Fi) ================================

TitleNET=WiFi

Net0=Upl.
Net1=Dnl.
Net2=Band
Net3=Protection
Net4=Time used

;OPTIONS ========================================

ConfigTxt=CONFIGURATION
SkinTipTxt=(PRESS ENTER TO SAVE THE CHANGES)
MusicTxt=(For a full list of supported music players and their respective player codes, check the NowPlaying plugin section of the Rainmeter manual)
PlayerTxt=Most used:  Name  ->  Code#CRLF#AIMP - AIMP3      ->  AIMP#CRLF#iTunes                   ->  iTunes#CRLF#MediaMonkey     -> MediaMonkey#CRLF#Winamp               ->  Winamp#CRLF#WindowsMediaPlayer ->   WMP#CRLF#foobar2000          ->  CAD#CRLF#MusicBee             ->  CAD#CRLF#VLC                       ->  CAD
LangTooltip="DE"= Deutch, "EN"= English, "FR"= Francais, "IT"= Italiano #CRLF#To create a new translation, go to @Resources folder, edit an #CRLF#existing one, save as... adding the new language abbreviation

NetTooltip=Measures in bytes, 500 kb= 524288, 1 Mb= 1048576 #CRLF#2 Mb= 2097152, 4 Mb= 4194304, 6 Mb= 6291456 #CRLF#10 Mb= 10485760, 20Mb= 20971520
NetTimeTooltip=0= Enabled, 1= Disabled
NetCounter=Enable Counter
NetShow=* this option to enable and show total time elapsed

HDDTxt=(Informations displayed in the Time skin)
HDDTooltip=Must contain the colon e.g. "C:"
HDD1Txt=Primary Drive Letter
HDD2Txt=Secondary Drive Letter
HDD3Txt=Third Drive Letter
HDD4Txt=Fourth Drive Letter
HDD5Txt=Fifth Drive Letter
HDDOnOffTooltip=Minimum 1, Maximum 5
HDDSTxt=Active Disks or partitions
USB1Txt=First Drive Letter
USB2Txt=Second Drive Letter
USB3Txt=Third Drive Letter
USBTooltip=Must contain the colon e.g. "H:", leave blank if not used
DVDInfo=ATTENTION: by inserting a disc, Rainmeter may freeze for a few seconds
RWText=DISKS ACTIVITY: Max Read/Write
RW1Txt=Primary Disk
RW2Txt=Other Disk/s
RWOpt1=HDD standard
RWOpt2=High-end HDD
RWOpt3=SSD standard
RWOpt4=High-end SSD
RWOpt0=No Disk

Lang1Txt=LANGUAGE
Lang2Txt=used
ExtCountry="DE":"Deutch","EN":"English","FR":"Francais","IT":"Italiano"

WebN=Website Name
WebAd=Web Address
WebTxt=To open your six preferred websites directly from the Time skin.

FeedDelayTxt=Alternation time         seconds
FeedRotTxt=Enable/disable pages alternation
FeedDelayTooltip=How long you see a page#CRLF#before to move to the next

ShTagTooltip=Maximum 27 letters if used without OTHER INFO#CRLF#Maximum 12 letters each one if both used
ShTagTooltip1=Maximum 12 letters

CloseLL1Txt0=Disable Launcher
CloseLL1Txt1=Enable Launcher
CloseLL1Explain=Launcher Disabled#CRLF#Use the command to the right

ChPathTxt=Choose path between Application and Folder
ChFileTxt=Application path
ChFolderTxt=Folder path

LLLabel=Name of application
LLLabel2=Name of folder
LLAppP=Application path
LLAppP2=Folder path
LLIco=Choose an icon

ProgramNum=Program Instances *              (Minimum 1, Maximum 4)
ProgramNumExpl=* MAXIMUM limit of concurrently active program instances, if allowed by the program.

FLD1L=FOLDER 1 - GROUP
FLDN=Name
Folder=FOLDER
FLDNam=Folder Name
FLDPat=Folder Path
FLD7L=FOLDER 7 - GROUP

SHTagTitle=Title Options
SHTagTop1=S.H.I.E.L.D. OS
SHTagTop2=Date complete
SHTagOth=OTHER INFO
ShTagOpt=Display Icon
ShTag0=Image
ShTag1=Text
ShTagIco=Choose image
ShTagT=Type text
SHTagTxt=(Add your Name or other displayed at the bottom of the S.H.I.E.L.D. Tag skin, change image on the right)

WeatUn1=°C Celsius
WeatUn2=°F Farhenheit
WeatCod=Location Code
UpdFr=Update Rate
SEC=seconds

WeatAttn=IMPORTANT! Set this section AFTER you have configured ALL THE REST, if you are connected to internet.
WeatTXt1=*WARNING! A request is send to the weather server with this frequency! Use 1800 (30 minutes, minimum), 2700 (45 minutes), 3600 (1 hour) or more. MANTAIN the original setting, you can be BLOCKED or BANNED from the site if you send too many update requests!
WeatTxt2=(To find the Code of your location: Go to http://www.weather.com and search for your city. Once in the webpage, go to the address bar and copy the 8 digit code (for example - USDC0001), and paste it on the Location Code. You can use the website, http://weather.yahoo.com or others, for the weather data, but very carefully, because the information format may be not utilizable)

SySMonTxt=You need Speedfan to read hardware informations. Go to http://www.almico.com/speedfan.php. Install the program, click "Exotics" label, if nothing appears, click "Show the magic" button and find what to show.#CRLF#First, top left, is "Fan 0", the next to the right is "Fan 1" and so on.

SySUn=UNITS (°C or °F)
SysUnTxt=Must be the same as in SpeedFan settings.
SensorN=SENSOR NUMBER
NOSensors=Disable

SysAlTxt=OVERHEATHING TEMPERATURE ALERT SETTINGS
FanAlTxt=FAN LOW RPM ALERT SETTINGS
CPUFLw=Fan Low rpm

FanTxt=When a sensor reaches the alert setting, the corresponding meter is highlighted with a red color.
SoundAlm=SOUND ALARMS
AlarmSTemp=Temperature Alarm
AlarmSFan=Fans Alarm
AlarmTempTxt=* Select the .wav sound to be used for the alarms, leave empty if not used.
CPUCoresTxt1=To verify the number of CPU Cores, click on
CPUCoresTxt2=In the PERFORMANCE section, count the windows number, next to CPU UTILIZATION, every window is a Core.
CPUOptTxt=CPU Graphics
CPUTxt1=CPU and Cores
CPUTxt2=Cores only

;UTILITY BUTTONS ================================

TitleUB2=Search
TitleUB3=Guide
Search1=Search files and programs
Search2=Search in Internet
TitleList=Search options
Comm1List=Search in Computer
Comm2List=Search with Google
Comm3List=Search with Yahoo
Comm4List=Search with Bing
