
[Variables]

;LARGE LAUNCHER BUTTONS =========================

;Hide Launcher 1 --------------------------------

CloseLL1=0
TimeNorm=1
TimePlus=0

;------------------------------------------------

;Program Name
;Program Path
;Program Icon

LLT1=Program 1
LLP1=C:\Windows\notepad.exe
LLI1=%UserProfile%\Documents\Rainmeter\Skins\Avengers\@Resources\Images\Icons\P1a.png

LLT2=Program 2
LLP2=C:\Windows\notepad.exe
LLI2=%UserProfile%\Documents\Rainmeter\Skins\Avengers\@Resources\Images\Icons\P2a.png

LLT3=Program 3
LLP3=C:\Windows\notepad.exe
LLI3=%UserProfile%\Documents\Rainmeter\Skins\Avengers\@Resources\Images\Icons\P3a.png

LLT4=Program 4
LLP4=C:\Windows\notepad.exe
LLI4=%UserProfile%\Documents\Rainmeter\Skins\Avengers\@Resources\Images\Icons\P4a.png

LLT5=Program 5
LLP5=C:\Windows\notepad.exe
LLI5=%UserProfile%\Documents\Rainmeter\Skins\Avengers\@Resources\Images\Icons\P5a.png

LLT6=Program 6
LLP6=C:\Windows\notepad.exe
LLI6=%UserProfile%\Documents\Rainmeter\Skins\Avengers\@Resources\Images\Icons\P6a.png

LLT7=Program 7
LLP7=C:\Windows\notepad.exe
LLI7=%UserProfile%\Documents\Rainmeter\Skins\Avengers\@Resources\Images\Icons\P7a.png

;------------------------------------------------

LLData1=HPScan.exe
LLData2=HPScan.exe
LLData3=HPScan.exe
LLData4=HPScan.exe
LLData5=HPScan.exe
LLData6=HPScan.exe
LLData7=HPScan.exe
ProgLL1=1
ProgLL2=1
ProgLL3=1
ProgLL4=1
ProgLL5=1
ProgLL6=1
ProgLL7=1
Type1=
Type2=
Type3=
Type4=
Type5=
Type6=
Type7=

;SMALL LAUNCHER BUTTONS =========================

;Hide Launchers ---------------------------------

CloseSL1=0
CloseSL2=0
CloseSL3=0
CloseSL4=0

;------------------------------------------------

SLT1=Program 1
SLP1=C:\Windows\notepad.exe
SLI1=%UserProfile%\Documents\Rainmeter\Skins\Avengers\@Resources\Images\Icons\P1a.png

SLT2=Program 2
SLP2=C:\Windows\notepad.exe
SLI2=%UserProfile%\Documents\Rainmeter\Skins\Avengers\@Resources\Images\Icons\P2a.png

SLT3=Program 3
SLP3=C:\Windows\notepad.exe
SLI3=%UserProfile%\Documents\Rainmeter\Skins\Avengers\@Resources\Images\Icons\P3a.png

SLT4=Program 4
SLP4=C:\Windows\notepad.exe
SLI4=%UserProfile%\Documents\Rainmeter\Skins\Avengers\@Resources\Images\Icons\P4a.png

SLT5=Program 5
SLP5=C:\Windows\notepad.exe
SLI5=%UserProfile%\Documents\Rainmeter\Skins\Avengers\@Resources\Images\Icons\P5a.png

SLT6=Program 6
SLP6=C:\Windows\notepad.exe
SLI6=%UserProfile%\Documents\Rainmeter\Skins\Avengers\@Resources\Images\Icons\P6a.png

SLT7=Program 7
SLP7=C:\Windows\notepad.exe
SLI7=%UserProfile%\Documents\Rainmeter\Skins\Avengers\@Resources\Images\Icons\P7a.png

SLT8=Program 8
SLP8=C:\Windows\notepad.exe
SLI8=%UserProfile%\Documents\Rainmeter\Skins\Avengers\@Resources\Images\Icons\P8a.png

SLT9=Program 9
SLP9=C:\Windows\notepad.exe
SLI9=%UserProfile%\Documents\Rainmeter\Skins\Avengers\@Resources\Images\Icons\P9a.png

;------------------------------------------------

SL9Mon=0
MaxL1=1
MaxL2=1
MaxL3=1
MaxL4=1
MaxL5=1
MaxL6=1
MaxL7=1
MaxL8=1
MaxL9=1
SL9Data1=HPScan.exe
SL9Data2=HPScan.exe
SL9Data3=HPScan.exe
SL9Data4=HPScan.exe
SL9Data5=HPScan.exe
SL9Data6=HPScan.exe
SL9Data7=HPScan.exe
SL9Data8=HPScan.exe
SL9Data9=HPScan.exe
ProgSL1=1
ProgSL2=1
ProgSL3=1
ProgSL4=1
ProgSL5=1
ProgSL6=1
ProgSL7=1
ProgSL8=1
ProgSL9=1
Type1S=
Type2S=
Type3S=
Type4S=
Type5S=
Type6S=
Type7S=
Type8S=
Type9S=

;SMALL LAUNCHER 2 BUTTONS =======================

SLT10=Program 1
SLP10=C:\Windows\notepad.exe
SLI10=%UserProfile%\Documents\Rainmeter\Skins\Avengers\@Resources\Images\Icons\P1a.png

SLT11=Program 2
SLP11=C:\Windows\notepad.exe
SLI11=%UserProfile%\Documents\Rainmeter\Skins\Avengers\@Resources\Images\Icons\P2a.png

SLT12=Program 3
SLP12=C:\Windows\notepad.exe
SLI12=%UserProfile%\Documents\Rainmeter\Skins\Avengers\@Resources\Images\Icons\P3a.png

SLT13=Program 4
SLP13=C:\Windows\notepad.exe
SLI13=%UserProfile%\Documents\Rainmeter\Skins\Avengers\@Resources\Images\Icons\P4a.png

SLT14=XP Mode
SLP14=%UserProfile%\Virtual Machines\Windows XP Mode.vmcx
SLI14=%UserProfile%\Documents\Rainmeter\Skins\Avengers\@Resources\Images\Icons\XPMode.png

;------------------------------------------------

SL2Data10=HPScan.exe
SL2Data11=HPScan.exe
SL2Data12=HPScan.exe
SL2Data13=HPScan.exe
SL2Data14=VMWindow.exe
ProgSL10=0
ProgSL11=0
ProgSL12=0
ProgSL13=0
ProgSL14=0
Type10s=
Type11s=
Type12s=
Type13s=
Type14s=

;FOLDER LAUNCHER BUTTONS ========================

;LEFT -------------------------------------------

;General Name (if plus is used)

FPLN11=Folder L

;Launchers Name (if plus is used)
;Launchers Path (if plus is used)

FPL1=C:\Program Files\Rainmeter\Options10.ini
FPLN1=Folder 1L

FPL2=C:\Program Files\Rainmeter\Options10.ini
FPLN2=Folder 2L

FPL3=C:\Program Files\Rainmeter\Options10.ini
FPLN3=Folder 3L

FPL4=C:\Program Files\Rainmeter\Options10.ini
FPLN4=Folder 4L

FPL5=C:\Program Files\Rainmeter\Options10.ini
FPLN5=Folder 5L

FPL6=C:\Program Files\Rainmeter\Options10.ini
FPLN6=Folder 6L

FPL7=C:\Program Files\Rainmeter\Options10.ini
FPLN7=Folder 7L

FPL8=C:\Program Files\Rainmeter\Options10.ini
FPLN8=Folder 8L

FPL9=C:\Program Files\Rainmeter\Options10.ini
FPLN9=Folder 9L

FPL10=C:\Program Files\Rainmeter\Options10.ini
FPLN10=Folder 10L

;------------------------------------------------

;Folder 1 Name (if plus not used)
;Folder 1 Name (if plus not used)

FLP1=C:\Program Files\Rainmeter\Options10.ini
FLN1=Folder 1

;------------------------------------------------

;Folder Path
;Folder Name

FLP2=C:\Program Files\Rainmeter\Options10.ini
FLN2=Folder 2

FLP3=C:\Program Files\Rainmeter\Options10.ini
FLN3=Folder 3

FLP4=C:\Program Files\Rainmeter\Options10.ini
FLN4=Folder 4

FLP5=C:\Program Files\Rainmeter\Options10.ini
FLN5=Folder 5

FLP6=C:\Program Files\Rainmeter\Options10.ini
FLN6=Folder 6

;RIGHT ------------------------------------------

;General Name (if plus is used)

FPRN11=Folder R

;Launchers Name (if plus is used)
;Launchers Path (if plus is used)

FPR1=C:\Program Files\Rainmeter\Options10.ini
FPRN1=Folder 1R

FPR2=C:\Program Files\Rainmeter\Options10.ini
FPRN2=Folder 2R

FPR3=C:\Program Files\Rainmeter\Options10.ini
FPRN3=Folder 3R

FPR4=C:\Program Files\Rainmeter\Options10.ini
FPRN4=Folder 4R

FPR5=C:\Program Files\Rainmeter\Options10.ini
FPRN5=Folder 5R

FPR6=C:\Program Files\Rainmeter\Options10.ini
FPRN6=Folder 6R

FPR7=C:\Program Files\Rainmeter\Options10.ini
FPRN7=Folder 7R

FPR8=C:\Program Files\Rainmeter\Options10.ini
FPRN8=Folder 8R

FPR9=C:\Program Files\Rainmeter\Options10.ini
FPRN9=Folder 9R

FPR10=C:\Program Files\Rainmeter\Options10.ini
FPRN10=Folder 10R

;------------------------------------------------

;Folder 7 Name (if plus not used)
;Folder 7 Name (if plus not used)

FLP7=C:\Program Files\Rainmeter\Options10.ini
FLN7=Folder 7

;DISK DRIVE LETTERS =============================

disk1=C:
disk2=D:
disk3=E:
disk4=H:
disk5=I:

usb1=J:
USB1On=0
usb2=K:
USB2On=0
usb3=Q:
USB3On=0

DVD1=F:
DVD1On=0

HideHDDS=5

MaxDiskRWC=104857600
ValueC1=50
ValueC2=100

MaxDiskRW=104857600
Value1=50
Value2=100

;CLOCK WEBPAGES =================================

;Webpage Name
;Webpage Address

WN1=Rainmeter DA
WA1=http://rainmeter.deviantart.com/

WN2=deviantART
WA2=http://deviantart.com/

WN3=Rainmeter
WA3=http://rainmeter.net/cms/

WN4=Rainmeter Forum
WA4=http://rainmeter.net/forum/

WN5=Twitter
WA5=http://www.twitter.com

WN6=Facebook
WA6=http://www.facebook.com

;MUSIC PLAYER ===================================

Player=WMP

;LANGUAGE =======================================

Country=EN

;NETWORK/Wi-Fi ==================================

NetTime=0

MaxUpload=1048576
MaxDownload=1048576

;RSS FEED =======================================

NewsURLFeed1=http://rainmeter.net/forum/feed.php

NewsURLFeed2=http://www.thepaperwall.com/rss.topfour.php

NewsURLFeed3=http://feeds.arstechnica.com/arstechnica/index

NewsURLFeed4=http://backend.deviantart.com/rss.xml?q=gallery%3Afonpaolo

FeedRot=0
FeedDelay=20

;SHIELD TAG DISPLAY =============================

;Name and other info displayed on the bottom

STName=User
STOther=Other
NoTagTitle=0
SignIcon=%UserProfile%\Documents\Rainmeter\Skins\Avengers\@Resources\Images\Shield Tag\Sign1.png
NoTagSign=0
NoTagText=1
NoTagDate=1
TagTxt=103
NoTagText=1

;WEATHER FORECAST SETTINGS ======================

OWN1=weather.com
OWA1=http://www.weather.com/
OLOC1=ITLZ2120
OTUPD=1800

WFUN=C
Unit=m

;SYSTEM MONITOR SETTINGS ========================

SFUN=C
CPUSF1=10
CPUSF2=11
CPUSF3=12
CPUSF4=13
MBSF1=0
MBSF2=4
GPUSF1=14
HDD1SF=7
HDD2SF=9
HDD3SF=8
HDD4SF=6
CPUFSF=1
SYSFSF=0

NoHD2=0
NoHD3=0
NoHD4=0
NoSysF=0

NoCPU=0
NoCPUGraph=1
YPos0=64

Alarm1=C:\Users\home\Documents\Rainmeter\Skins\Avengers\Sys Monitor\Alarm.wav
Alarm2=C:\Users\home\Documents\Rainmeter\Skins\Avengers\Sys Monitor\Alarm.wav

;ALERT SETTINGS ---------------------------------

CPUOHSF=70
MB1OHSF=65
MB2OHSF=65
GPUOHSF=75
HDDOHSF=55
CPUMRSF=500
SYSMRSF=500

;CALENDAR SETTINGS ==============================

StartDay=1
WeekN=W

;UTILITY BUTTONS ================================

UB1=%UserProfile%\Documents
TitleUB1=Documents

UB3=%UserProfile%\Documents\Rainmeter\Skins\Avengers\S.H.I.E.L.D. OS documentation.pdf
;TitleUB3 -> Change name in LanguageXX.inc, where XX is DE, EN, FR, IT or any other added.

UB4=%UserProfile%\Downloads
TitleUB4=Downloads

UB5=%UserProfile%\Pictures
TitleUB5=Images

UB6=%UserProfile%\Videos
TitleUB6=Videos
