
[TitleStyle]
FontFace=Helvetica Bold
FontColor=0,0,0
AntiAlias=1
FontSize=12

[ContentStyle]
FontFace=HelvLight Regular
AntiAlias=1
FontColor=0,0,0
DynamicVariables=1
FontSize=12

[HighTempStyle]
FontFace=HelvLight Regular
AntiAlias=1
FontColor=0,0,0
DynamicVariables=1
FontSize=15

[LowTempStyle]
FontFace=HelvLight Regular
AntiAlias=1
FontColor=0,0,0
DynamicVariables=1
FontSize=12

[IconStyle]
ImagePath=#IconPath#
AntiAlias=1
DynamicVariables=1
W=45
H=45

[IconStyleSmall]
ImagePath=#IconPath#
AntiAlias=1
DynamicVariables=1
W=35
H=35