[Rainmeter]
Update=10

[Variables]

[Tab1]
Meter=Button
ButtonImage=bin.png
X=92
Y=159
W=100
H=100
LeftMouseUpAction=!Execute [!ShowMeterGroup button][!HideMeter Tab1][!Redraw]
[Tab2]
Meter=button
ButtonImage=bin1.png
Group=button
X=92
Y=159
LeftMouseUpAction=!Execute [!HideMeterGroup button][!ShowMeter Tab1][!Redraw]
Hidden=1
[1]
Meter=Button
ButtonImage=button1.png
Group=button
X=46
Y=79
LeftMouseUpAction=!Execute ["#CURRENTPATH#ItemPaths\item1.lnk"][!Redraw]
RightMouseUpAction=!Execute ["#CURRENTPATH#Tools\LauncherL.exe" App2 1 "#PROGRAMPATH#" "#CURRENTCONFIG#"]
Hidden=1

[2]
Meter=Button
ButtonImage=button5.png
Group=button
X=0
Y=0
LeftMouseUpAction=!Execute ["#CURRENTPATH#ItemPaths\item2.lnk"][!Redraw]
RightMouseUpAction=!Execute ["#CURRENTPATH#Tools\LauncherL.exe" App2 2 "#PROGRAMPATH#" "#CURRENTCONFIG#"]
Hidden=1

[3]
Meter=Button
ButtonImage=button3.png
Group=button
X=184
Y=106
LeftMouseUpAction=!Execute ["#CURRENTPATH#ItemPaths\item3.lnk"][!Redraw]
RightMouseUpAction=!Execute ["#CURRENTPATH#Tools\LauncherL.exe" App2 3 "#PROGRAMPATH#" "#CURRENTCONFIG#"]
Hidden=1

[4]
Meter=Button
ButtonImage=button2.png
Group=button
X=92
Y=0
LeftMouseUpAction=!Execute ["#CURRENTPATH#ItemPaths\item4.lnk"][!Redraw]
RightMouseUpAction=!Execute ["#CURRENTPATH#Tools\LauncherL.exe" App2 4 "#PROGRAMPATH#" "#CURRENTCONFIG#"]
Hidden=1

[5]
Meter=Button
ButtonImage=button4.png
Group=button
X=138
Y=26
LeftMouseUpAction=!Execute ["#CURRENTPATH#ItemPaths\item5.lnk"][!Redraw]
RightMouseUpAction=!Execute ["#CURRENTPATH#Tools\LauncherL.exe" App2 5 "#PROGRAMPATH#" "#CURRENTCONFIG#"]
Hidden=1

[6]
Meter=Button
ButtonImage=button2.png
Group=button
X=45
Y=185
LeftMouseUpAction=!Execute ["#CURRENTPATH#ItemPaths\item6.lnk"][!Redraw]
RightMouseUpAction=!Execute ["#CURRENTPATH#Tools\LauncherL.exe" App2 6 "#PROGRAMPATH#" "#CURRENTCONFIG#"]
Hidden=1

[7]
Meter=Button
ButtonImage=button4.png
Group=button
X=184
Y=160
LeftMouseUpAction=!Execute ["#CURRENTPATH#ItemPaths\item7.lnk"][!Redraw]
RightMouseUpAction=!Execute ["#CURRENTPATH#Tools\LauncherL.exe" App2 7 "#PROGRAMPATH#" "#CURRENTCONFIG#"]
Hidden=1

[8]
Meter=Button
ButtonImage=button5.png
Group=button
X=0
Y=212
LeftMouseUpAction=!Execute ["#CURRENTPATH#ItemPaths\item8.lnk"][!Redraw]
RightMouseUpAction=!Execute ["#CURRENTPATH#Tools\LauncherL.exe" App2 8 "#PROGRAMPATH#" "#CURRENTCONFIG#"]
Hidden=1

[9]
Meter=Button
ButtonImage=button2.png
Group=button
X=138
Y=133
LeftMouseUpAction=!Execute ["#CURRENTPATH#ItemPaths\item9.lnk"][!Redraw]
RightMouseUpAction=!Execute ["#CURRENTPATH#Tools\LauncherL.exe" App2 9 "#PROGRAMPATH#" "#CURRENTCONFIG#"]
Hidden=1

[10]
Meter=Button
ButtonImage=button3.png
Group=button
X=138
Y=240
LeftMouseUpAction=!Execute ["#CURRENTPATH#ItemPaths\item10.lnk"][!Redraw]
RightMouseUpAction=!Execute ["#CURRENTPATH#Tools\LauncherL.exe" App2 10 "#PROGRAMPATH#" "#CURRENTCONFIG#"]
Hidden=1

[11]
Meter=Button
ButtonImage=button2.png
Group=button
X=46
Y=26
LeftMouseUpAction=!Execute ["#CURRENTPATH#ItemPaths\item11.lnk"][!Redraw]
RightMouseUpAction=!Execute ["#CURRENTPATH#Tools\LauncherL.exe" App2 11 "#PROGRAMPATH#" "#CURRENTCONFIG#"]
Hidden=1

[12]
Meter=Button
ButtonImage=button3.png
Group=button
X=92
Y=212
LeftMouseUpAction=!Execute ["#CURRENTPATH#ItemPaths\item12.lnk"][!Redraw]
RightMouseUpAction=!Execute ["#CURRENTPATH#Tools\LauncherL.exe" App2 12 "#PROGRAMPATH#" "#CURRENTCONFIG#"]
Hidden=1

[13]
Meter=Button
ButtonImage=button1.png
Group=button
X=0
Y=106
LeftMouseUpAction=!Execute ["#CURRENTPATH#ItemPaths\item13.lnk"][!Redraw]
RightMouseUpAction=!Execute ["#CURRENTPATH#Tools\LauncherL.exe" App2 13 "#PROGRAMPATH#" "#CURRENTCONFIG#"]
Hidden=1

[14]
Meter=Button
ButtonImage=button5.png
Group=button
X=92
Y=106
LeftMouseUpAction=!Execute ["#CURRENTPATH#ItemPaths\item14.lnk"][!Redraw]
RightMouseUpAction=!Execute ["#CURRENTPATH#Tools\LauncherL.exe" App2 14 "#PROGRAMPATH#" "#CURRENTCONFIG#"]
Hidden=1

[15]
Meter=Button
ButtonImage=button4.png
Group=button
X=138
Y=79
LeftMouseUpAction=!Execute ["#CURRENTPATH#ItemPaths\item15.lnk"][!Redraw]
RightMouseUpAction=!Execute ["#CURRENTPATH#Tools\LauncherL.exe" App2 15 "#PROGRAMPATH#" "#CURRENTCONFIG#"]
Hidden=1